/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libCifrador_CifradorCesar */

#ifndef _Included_libCifrador_CifradorCesar
#define _Included_libCifrador_CifradorCesar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libCifrador_CifradorCesar
 * Method:    cifrarCesar
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libCifrador_CifradorCesar_cifrarCesar
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     libCifrador_CifradorCesar
 * Method:    descifrarCesar
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libCifrador_CifradorCesar_descifrarCesar
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
